### ISSUE TITLE
Create rake task for adding new org members

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1004]

**Comment by pkarman** [comment]
examples:
  
   single User
   % rake users:create['Jill','jill@someplace.com']
   
   simple User in an Org with id 123
   % rake users:create['Jill','jill@someplace.com'] ORG_ID=123
  
   list of Users in Org 456
   % cat users
   Joe, joe@foo.com
   Jill, jill@bar.edu
   % rake users:create_from_file[users] ORG_ID=456
  
   add existing Users to an org 789
   % cat users
   joe@foo.com
   jill@bar.com
   % rake users:add_to_org[users] ORG_ID=789
  
   use the DRY_RUN=1 env var to validate data without actually writing to the db.
   use the VERBOSE=1 env var to print out values as they are processed.

**Comment by pkarman** [comment]
This is not user-facing, so really not for Tara to test.

@Saltzshaker do you want to try it? Otherwise we can just deploy and test it whenever the next occasion arises.

I should not that running this with a file via the heroku one-off worker dyno method will not work since that file will not be available to the dyno. For production, probably easiest to run it via the uploads.popuparchive.com server. For that, I just need a ssh key so I can add whomever needs to use it to the authorized users list.

**Comment by Saltzshaker** [comment]
sure, i'll try it out in my dev environment with a fake user

**Comment by pkarman** [comment]
going to deploy this with dolly and @Saltzshaker we can test it at your leisure.
