### ISSUE TITLE
Collection sort broken

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1017]
https://www.popuparchive.com/collections/1754?sortBy=date_created&sortOrder=desc
https://www.popuparchive.com/collections/1754?sortBy=date_added&sortOrder=desc

**Comment by pkarman** [comment]
there are few things going on here.

(1) the initial drop-down selection was wrong when the sortBy/sortOrder params were explicit in the URL. That has been fixed in dolly in fe08605ae20a22b8ffef53bd4a0d8cb6bb597e05

(2) the data can be misleading. The "Created:" date displayed in the search results partial uses, in order of defined-ness, the date_created or the date_added values from the Item. The **date_created** value is manually assigned on the Item; the **date_added** value is really the *created_at* auto-assigned timestamp used by Rails. So if there isn't a manually added (and by "manual" I mean "by the user" or "programmatically by a feed importer") then it will fallback to the db record created_at value.

However the sort itself happens on the server, where the **date_created** value might be nil, so all the nil values will sort "together" and depending on the particular result set, will give weird appearance of being "out of order."

So it may be somewhat misleading to have separate "Date Created" and "Date Added" sortBy options, since the "Date Created" is really "Date Created or Date Added, whichever is defined".

(3) Finally, the real bug, is that the sort order determination was wrong in the search controller. It was preferring !query over explicit sortBy values, which should be reversed. That is fixed in dolly in a9d0dcc

**Comment by tarakieffer** [comment]
If I am reading @pkarman comments, this is expected results for a date sorted by Created.  Where the items with a user defined created date are sorted together and the other items are sorted together.  Correct?

![screen shot 2015-02-27 at 4 35 43 pm](https://cloud.githubusercontent.com/assets/9256525/6422505/0d67231a-be9f-11e4-854d-638b979e3a6f.png)

**Comment by annewootton** [comment]
Hmm, in a collection sorted "Oldest Created to Newest Created" it doesn't
seem to make sense to have 25 Feb 2015 come above Dec 02 2014, whatever the
underlying logic.

**Comment by pkarman** [comment]
@tarakieffer you are correct. The items with no **date_created** manual assignment will tend to group together because they are really *nil* values in the ES index.

@annewootton You are correct. That is a UX bug. It happens for the reasons I detail above.

The alternative would be to always populate the **date_created** field in the index, regardless of whether the user entered a value.

```
index[:date_created] = item.date_created || item.created_at
```

If we do that, we give up accuracy for usability. I don't have a strong opinion either way. My personal preference is usually for accuracy but I am not a PUA user so my preference here should not count.

**Comment by annewootton** [comment]
I get it now, thanks. If we always populate the date_created field in the index, regardless of whether the user entered a value, I think we'll make customers like Studs Terkel unhappy since we've imported date_created information from them at the item level for all of their items and they expect to be able to sort that data.

Crossing my fingers that Tara has found an edge case, and that most people either use date_created regularly (i.e. archives) or don't use it at all (i.e. newsrooms).

**Comment by tarakieffer** [comment]
Edge cases - oh, the satisfaction in finding them.   

Marking this as ready-to-deploy
