### ISSUE TITLE
Reprocess as premium without requiring CC info/adding to billing total?

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1026]
This happens sometimes when we want to test out a premium transcript for someone who's already uploaded audio to a Community plan, or (more of a fringe case) for Studs Terkel, who have an arrangement with us where they tell us premium transcripts they want and we reprocess them.

To date, Anne/Emily have been making themselves the owners of these files. The af.order_premium_transcript(af.user) doesn't work for these cases because it requires (understandably) that a CC be on file.

**Comment by pkarman** [comment]
Changing ownership of a collection/item/audio_file in order to get permission to act upon it is a pretty consistent theme in both workflow and the root of bug reports. We should stop re-assigning ownership to PUA employees when we want to act on a customer's behalf, and figure out a better way to do that.

In this case, I can check the order_premium_transcript() method to check the user argument for the superadmin role and allow that role *or* credit card on file.

So the new code snippet would look like:

```ruby
anne_user = User.find annes_id
af = AudioFile.find audio_id
af.order_premium_transcript( anne_user )
```

**Comment by pkarman** [comment]
I *think* that method change would also allow superadmin users to click the Re-order as Premium button from the UI and it will Just Work.

**Comment by annewootton** [comment]
This sounds great and an improvement over our hacky past.

ᐧ
