### ISSUE TITLE
Review PUA terms of use re: the API

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1053]

**Comment by annewootton** [comment]
I've tweaked the definition of the Archive Platform to include "application program interfaces, software, and data provided by such application program interfaces (collectively, including all data, the 'Platform'). Replicating for Audiosear.ch as well. We can open new tickets if/when we want to get more specific about metering/limits or create separate terms for the Audiosear.ch API.

Revised first paragraph:
"To achieve this ambitious goal we have created an archiving platform that includes application program interfaces, software, and data provided by such application program interfaces (collectively, including all data, the “Platform”) that is accessible at popuparchive.com (the “Site”). In order for us to operate the Platform and the Site (collectively the “Archive Service”) responsibly and effectively there are legal requirements we require our users to abide by in order to participate. We appreciate your understanding and are happy to answer any questions you have about this Agreement."

**Comment by annewootton** [comment]
See https://github.com/popuparchive/pop-up-archive/commit/bbe6991fcf1dc8bddde88d96ddb59b95b0ff29d4.

**Comment by annewootton** [comment]
Also added this sentence to 1.6 Prohibited Site Usage, per @pkarman's advice:
"When accessing the Archive Service through an applicaton programming interface, you may be subject to data limits to be imposed at the discretion of Pop Up Archive." Also replicating for Audiosear.ch.

See https://github.com/popuparchive/pop-up-archive/commit/01bdb2357fbf416f2a6d64b0d0d61994570e7566.
