### ISSUE TITLE
Subscribe to newsletter on homepage

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1097]

**Comment by Saltzshaker** [comment]
This needs to be tested is staging, and possibly production, in order to make sure people actually get added to the subscribe list. Right now in my dev environment I get this error when I click submit: "No route matches [POST] "/" Rails.root: /Users/saltzshaker/Desktop/sites/pop-up-archive2" ...but the url in the code, taken from mailchimp's embed form, still looks like it should lead to the right place when live: action="//popuparchive.us5.list-manage.com/subscribe/post?u=832c18aae4790d85320ab01da&amp;id=39650ec21b" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank"

Assigning to Bailey to merge and deploy to staging when the time comes

**Comment by tarakieffer** [comment]
![screen shot 2015-10-09 at 6 42 12 am](https://cloud.githubusercontent.com/assets/9256525/10392927/0b549fb4-6e51-11e5-8bda-c7b42be07377.png)
