### ISSUE TITLE
Big file not transcoding

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1102]
Keep an eye on this one: https://www.popuparchive.com/superadmin/audio_files/44184

Failed 4/29, was refired today, it's been five hours and transcode tasks seem to have expired.

**Comment by pkarman** [comment]
interesting that is seems to have been transcribed ok anyway:
https://www.popuparchive.com/superadmin/tasks/392070

I suspect that the fixer task timed out due to file length but that it may have subsequently tried again and succeeded. The .mp3 is required for speechmatics, and apparently it got created eventually:

```
curl -s -o /dev/null  -v -L https://www.popuparchive.com/media/audio_file/ac98/Pham_Thein_Khoc_Multi_Cam_Full_Interview_audio_only.mp3

< HTTP/1.1 200 OK
< x-amz-id-2: twI0D1Uv3tgB0WMJawca9vmX5WPvAjHiKCJFB9zTIB9NCvkhOz40RrYc/FCbaX9M
< x-amz-request-id: A74DC2D95A9C1961
< Date: Wed, 13 May 2015 15:29:32 GMT
< Content-Disposition: attachment; filename="Pham_Thein_Khoc_Multi_Cam_Full_Interview_audio_only.mp3"
< Last-Modified: Fri, 01 May 2015 00:11:07 GMT
< ETag: "eb2386659a78b2915e009f47cfa151a7"
< Accept-Ranges: bytes
< Content-Type: audio/mpeg
< Content-Length: 216812146
* Server AmazonS3 is not blacklisted
< Server: AmazonS3
```
