### ISSUE TITLE
"Upgrade plan" messaging on below-limit premium plan

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1141]
Check the processing alert logic so that right after uploading, the item pages for users on paid plans never get the 2-min preview alert, only an alert that says:
"Your Premium Transcript will be ready soon. We'll email you when the full transcript is loaded."

This looks like it could be the culprit in controllers.js.rb? 
```
else if (file.currentStatus == "<%= AudioFile::TRANSCRIBE_INPROCESS %>") {
      statusHTML += "<p>The first two minutes of your transcription will be ready momentarily. "; 
```

Reported 7/23: "the site says that the first two minutes will be available soon...that never seems to be the case. Or maybe I just don't know where to look?"

Another user on a premium plan said: "I just uploaded a 3 minute file and got a note that the first two minutes would be processed and "upgrade your plan for full transcript."" The file eventually finished processing with a Premium transcript.

**Comment by annewootton** [comment]
Try to recreate.

**Comment by annewootton** [comment]
This will also probably become moot with #815 since we won't be telling people to "upgrade your plan for full transcript" anymore if the community plan includes one hour of (full) premium transcripts. 

Though that raises the question of what the upgrade language should change to — "upgrade your plan for more premium transcripts" ? @baileyspace @Saltzshaker

**Comment by Saltzshaker** [comment]
Should we push this forward to the Community Plan milestone and rename "Figure out how to upsell from new community plan" ?

Some initial ideas, could be multi-pronged: 
1. When over hour, have message in email completion alert "Got more audio? Our monthly plans let you upload more audio at a better rate."

2. Once the hour (& change) is uploaded, show a full-page overlay, similar to the loading mask, that just says something like "Got more audio to transcribe? <pricing page link>Our monthly plans let you upload more audio at a better rate.</link> [...then in smaller text] Don't need a monthly plan? Continue to upload more audio and pay as you go.

**Comment by annewootton** [comment]
@Saltzshaker I think we should confirm that the processing logic is no longer flawed, so that premium plan members never get messaging intended for community plan members, regardless of what the messaging is. Moving this to the Community Plan milestone. We can discuss messaging for community plan members separately.

**Comment by annewootton** [comment]
For reference, reported 7/23: "the site says that the first two minutes will be available soon...that never seems to be the case. Or maybe I just don't know where to look?"

Check the processing alert logic so that right after uploading, the item pages for users on paid plans never get the 2-min preview alert, only an alert that says:
"Your Premium Transcript will be ready soon. We'll email you when the full transcript is loaded."

This looks like it could be the culprit in controllers.js.rb?

```else if (file.currentStatus == "<%= AudioFile::TRANSCRIBE_INPROCESS %>") {
      statusHTML += "<p>The first two minutes of your transcription will be ready momentarily. "; ```

**Comment by tarakieffer** [comment]
I have not observed the 2-min preview message in the files I have been uploading.  These are the two in-process messages I have seen.

![screen shot 2015-08-05 at 7 53 06 am](https://cloud.githubusercontent.com/assets/9256525/9086290/2945c088-3b49-11e5-9042-eea75ccc4284.png)
![screen shot 2015-08-05 at 7 46 24 am](https://cloud.githubusercontent.com/assets/9256525/9086322/5ae93476-3b49-11e5-820d-5738f55093e6.png)

**Comment by Saltzshaker** [comment]
observed in production...keep open for now.
