### ISSUE TITLE
Facet list on Explore page is broken

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1186]
Clicking "more" on the Explore page no longer works, it just opens up a page with the letters. Clicking the letters does not load new pages.
![screen shot 2015-07-31 at 9 11 37 am](https://cloud.githubusercontent.com/assets/8497203/9007940/29a08326-3764-11e5-9ffb-1134dc09052b.png)
https://popuparchive.com/explore

**Comment by pkarman** [comment]
just to clarify: the bug is evident when you click the 'More' link under any of the facet category columns on the /explore page. The URL it calls is:

https://www.popuparchive.com/api/search?facets[interviewers][regex]=A.*&facets[interviewers][regex_flags]=CASE_INSENSITIVE&facets[interviewers][size]=100

and there is a JS exception thrown:
```
TypeError: Cannot read property 'terms' of undefined
```

**Comment by annewootton** [comment]
Dependent on #1335.

**Comment by AndersEverett** [comment]
This works now for all facets/aggs except collection_id. Fixed with 217614c. Elasticsearch returns collection ids rather than collection titles, so this will be dealt with in  #1379. Either titles should be added to the index or some other solution. It's too slow to query each collection id and then alphabetize everything from angular.

**Comment by annewootton** [comment]
To clarify: #1379 will fix aggregation mappings for collection_id as well as all other facets besides tags and entities, which were fixed with this ticket.
