### ISSUE TITLE
Cancelled transcribe task

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1194]
Any idea why the transcribe task keeps getting cancelled? I haven't seen it in the dashboard either: https://www.popuparchive.com/superadmin/tasks?q%5Bowner_id_equals%5D=48922&q%5Bowner_type_equals%5D=AudioFile Other files in this collection processed successfully, it's only this one.

**Comment by pkarman** [comment]
the original file appears to be a 1.5 gig mp3 file, which is probably causing all the speechmatics tasks to time out due to memory limit constraints. I believe all the speechmatics task code runs in-memory so if the file is that big, it is what is causing our out of memory errors at heroku.

the customer should try a smaller file.

**Comment by Saltzshaker** [comment]
notified custy.
