### ISSUE TITLE
Allowed to upload when over limit

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1201]
This is Phylicia - 1 hour demo user over limit.  This should be gone, correct?
![screen shot 2015-08-18 at 2 46 04 pm](https://cloud.githubusercontent.com/assets/9256525/9340855/fe7d3510-45b7-11e5-9628-b3db3499bd45.png)

![screen shot 2015-08-18 at 2 46 31 pm](https://cloud.githubusercontent.com/assets/9256525/9340854/fe79a968-45b7-11e5-92d0-a7596665daef.png)

**Comment by pkarman** [comment]
I thought it was only on-demand (re-transcribe as Premium) that was supposed to be removed. Users can still pay the a la carte rate if they go over their limit, if they have a credit card on file.

@annewootton @baileyspace ?

**Comment by baileyspace** [comment]
We have "remove pay as you go" on the community plan ticket, which I
suppose could be interpreted as just remove pay as you go on the community
plan, but we intended that to mean to remove a la carte uploads all
together. In order to get more hours users should upgrade.
https://github.com/popuparchive/pop-up-archive/issues/1176.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-08-18 12:51 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by pkarman** [comment]
Ok, I will remove all pay-as-you-go.

**Comment by annewootton** [comment]
Yes, this was all documented in Slack on 7/23:
peter [12:36 PM] 
when we say "remove pay as you go" option, does that mean if a user on a paying plan attempts to upload more than their monthly allotment, the upload should be disallowed completely? right now they are just charged the on-demand price.

bailey [12:43 PM] 
Yes, they should upgrade to a larger plan if they hit their limit

**Comment by tarakieffer** [comment]
No audio allowed after reaching limit.

![screen shot 2015-08-19 at 8 24 33 am](https://cloud.githubusercontent.com/assets/9256525/9357290/c53c5eb8-464b-11e5-9d91-c722c955432d.png)
