### ISSUE TITLE
Redirect https://www.popuparchive.com/users/sign_up?plan_id=community to new community plan

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1278]
Users with old links are able to sign up for the old plan.

**Comment by annewootton** [comment]
Here's the link to the new community plan: https://www.popuparchive.com/users/sign_up?plan_id=premium_community

**Comment by tarakieffer** [comment]
https://pop-up-archive-staging.herokuapp.com/users/sign_up?plan_id=community  is not redirecting to https://pop-up-archive-staging.herokuapp.com/users/sign_up?plan_id=premium_community

When I sign up through both links, it appears I am signing up for the same plan.

![screen shot 2015-10-30 at 12 58 50 pm](https://cloud.githubusercontent.com/assets/9256525/10853797/0edabb62-7f06-11e5-8a41-156f95e5de9e.png)

**Comment by AndersEverett** [comment]
I should have specified that I didn't change the url redirect since devise made that tricky. Instead, the variable has been changed so that anyone with the community plan link automatically gets signed up for the premium_community account. It looks like that the behavior you're seeing is the correct behavior.

**Comment by tarakieffer** [comment]
Super.  Marking ready-to-deploy.
