### ISSUE TITLE
Why does this search query return a 403 privacy error?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1292]
https://www.popuparchive.com/error/403?was=https:%2F%2Fwww.popuparchive.com%2Fsearch%3Fpage%3D1%26query%3Dabortion%2520diaries

**Comment by AndersEverett** [comment]
Other search issue when searching names of collections: "99% invisible" returns "oops. the server had a problem."

**Comment by Saltzshaker** [comment]
@AndersEverett @baileyspace could this be a wildcard character issue with "%"? 

@baileyspace I thought we had put in fixed for that in the past, but wasn't able to find a past ticket. Maybe it was only for Audiosear.ch: https://github.com/popuparchive/audiosear.ch/issues/194

In either case, I think this is a separate issue from the privacy error.

**Comment by AndersEverett** [comment]
The query seems to have parsed the "%" character correctly ('&query=99%25+invisible'), so I don't think so; but yes, separate issue.

**Comment by AndersEverett** [comment]
In dev environment this collection was set to items_visible_by_default = false while some of the items were set to is_public = true. Changing all item to is_public = false fixed privacy error and rendered correct search results. Ready for fix in production db.

**Comment by Saltzshaker** [comment]
@AndersEverett Create list of other collections with mismatched is_public/items_visible_by_default settings.

**Comment by AndersEverett** [comment]
Original query issue has been rectified in production db and is ready to test. I ran a script to find other instances of mismatches and found two more collections with private collections and public items. These were 5721 & 5055. These are also fixed in the production database as they were causing similar errors. There are four collections with public collections containing private items, and these don't create errors. These are 3850, 4324, 4330, and 4498.

**Comment by Saltzshaker** [comment]
5721 was deleted. 5055, 3850, 4324, 4330, and 4498 all now appear with "This page is private" messaging.

Original query now works!
