### ISSUE TITLE
Make sure that only basic transcripts can be overwritten

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1305]
For example, basic overwrote a premium transcript for this file: https://www.popuparchive.com/superadmin/tasks?q%5Bowner_id_equals%5D=42500&q%5Bowner_type_equals%5D=AudioFile

**Comment by annewootton** [comment]
And in fact, premium transcribe tasks shouldn't overwrite existing premium
transcripts. So perhaps a better ticket would be: Make sure that only basic
transcripts can be overwritten. Eh?

**Comment by Saltzshaker** [comment]
@annewootton what about cases where we WANT to overwrite another premium transcript because something went wrong with the original VB transcript? 
It seems to me the keys things are:
* prevent basic from overwriting premium
* if premium overwrites premium, make sure we save both transcripts in case the first one was edited (is this already true?)
What do you think?

**Comment by annewootton** [comment]
That seems like a lot of engineering for what should be fringe cases/bugs. If we need to re-transcribe a premium item I'd just as soon have us or the user re-upload the audio. 

Also, you mention not letting basic overwrite premium but I thought this ticket was to make sure only premium can only overwrite basic. There shouldn't be basic transcripts at all...

**Comment by Saltzshaker** [comment]
So this ticket was actually triggered by a basic transcript overwriting a premium transcript, which is in the ticket description. Then I think I changed the title based on your suggestion without thinking about it too much. But in fact Anders did just finish the ticket to allow refiring transcripts in the event of a VB bug, so I see no need to disable that premium-overwriting-premium function now.  

Agreed that the basic-overwriting-premium is a fringe case, it was just disturbing to know this could happen. I'd be good with making "prevent basic from overwriting premium" a low ticket in general to do. Or we could just close it.

**Comment by annewootton** [comment]
Oh yeah, thanks for reminding me of the comments — the reason I suggested
the ticket revision (only allow basic to get overwritten) is because I
wanted to protect existing premium transcripts from getting accidentally
overwritten by new premium transcripts too. I didn't mean that the basic
overwriting premium is an edge case, I actually meant that wanting to
replace premium with premium seems like an edge case.

BUT that being said I'm down with the "refire transcript" button, forgot
about that, and not worried if we save the originals in those cases b/c our
whole intention is to reprocess them. And the fact that basic transcripts
are firing in the first place might deserve a separate ticket, using this
item as example.

As for a safeguard just in case transcribe tasks do randomly fire, upon
closer inspection, in our previous comments neither of us accounted for a
use case where there are basic transcripts that have been edited (i.e.
Studs) and therefore shouldn't be overwritten even by premium.

So... we might have two tickets here: 1) don't allow basic transcripts on
any items and 2) don't allow edited transcripts to be replaced, ever.

**Comment by Saltzshaker** [comment]
We are closing this in favor of https://github.com/popuparchive/pop-up-archive/milestones/Mencken
