### ISSUE TITLE
Write report to notify us if transcribe jobs are "accepted" for an unacceptable amount of time

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1403]
How long, you ask? I'm not sure. Maybe 24 hours?

**Comment by baileyspace** [comment]
And to nudger rake tasks individual tasks in fixer.rake. Email edison if it's outside the anticipated turnaround time.

**Comment by AndersEverett** [comment]
e5fdc3f sends to Edison if 'accepted' state over 18hrs. Nudger appears to look back only 24 hours for missing transcripts, so set window 18-24 hrs out.

**Comment by annewootton** [comment]
Discussed with @AndersEverett and @baileyspace and the email will send if 'accepted' state is over 3hrs.

**Comment by Saltzshaker** [comment]
@baileyspace, any ideas for testing this? @AndersEverett isn't sure how to recreate the 'accepted' state, or whether it's a good idea to do so

**Comment by Saltzshaker** [comment]
@AndersEverett will test this by faking the response in staging and seeing if the report sends.

@AndersEverett can you also double-check that when a voicebase task returns "failed" status we do indeed fire a new transcript, since apparently that didn't happen for these three files from 4/13-4/14? All were stuck in 'working' until I manually fired new transcribe tasks. When I ran 'finish_task' on the initial working tasks, it returned the error: "Cannot finish task where VB status != finished (failed)"
https://www.popuparchive.com/superadmin/tasks/519441
https://www.popuparchive.com/superadmin/tasks/519733
https://www.popuparchive.com/superadmin/tasks/519722

If not, let's open up a new ticket.

**Comment by annewootton** [comment]
Also, to clarify for testing: faking the response in staging should be done
via an rspec test.
ᐧ

**Comment by AndersEverett** [comment]
Since method in rake task relies on checking the remote media object, @baileyspace agrees an rspec test wouldn't effectively check the state necessary to fire off the email. Will test when situation arises in production.
