### ISSUE TITLE
Allow org admins to add org members

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#583]

**Comment by pkarman** [comment]
This has serious security issues, particularly in light of #951 since adding a user to an org now alters that user's collections. Allowing an org admin to arbitrarily add users to their org gives them the power to "own" any item in the database.

There are a couple ways to go:

* make org team management a feature of the /superadmin screen, restricting the use to site admins. This is the safest but requires some work for PUA.
* make org team membership initiated by the user ("add me to this team") and approved by the org owner/admin. This requires that both org admin and user agree on the team assignment. We can make the workflow pretty easy (email with one-token for admins to click).

**Comment by pkarman** [comment]
This one needs some more thought and definitely won't be done by tomorrow.

**Comment by pkarman** [comment]
org-invite branch created.

**Comment by pkarman** [comment]
this feature was branched from the linda branch so should wait to create a PR till after linda is merged.

**Comment by pkarman** [comment]
to ease the branch merging, I pulled this into the linda-rc branch.

**Comment by tarakieffer** [comment]
Admins are able to add an existing user to the org  by entering the email address on the Organization page.

If the email is not associated with an existing user, an error displays "There was a problem sending the invite."

![screen shot 2015-08-21 at 11 47 35 am](https://cloud.githubusercontent.com/assets/9256525/9413912/810ffcf8-47fa-11e5-9402-fa37a7f5b46d.png)

Email is sent to user.  Clicking link in email, adds user as a member to the organization.  

Marking as ready-to-deploy.
