### ISSUE TITLE
mask/proclaim on UI page while API calls are finishing

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#596]
give the user some feedback that the page isn't yet completely finished.

example: http://stage.popuparchive.com/search?page=1&query=test

**Comment by tarakieffer** [comment]
Mask is displaying for searches, uploads, saving of edits, and navigation to My Collections page.  

Some scenarios seem to take longer for the page to load, but I saw no examples where the mask didn't go away.   Performance does not seem to have degraded, but will probably be more noticeable to users since they are not able to continue with navigation.
