### ISSUE TITLE
Tag visualization not updating/showing correct count

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#807]
For organization #3, for example, the popuparchive.com/analytics page says there are 6 items across 9 collections tagged "frank sinatra: live at melbourne hall" — however, there are many more than that.

I can't tell which six items it happens to be counting for this tag. When I remove collections from the /analytics visualization, the count drops — but again, these collections each have many mentions of the tag in question.

**Comment by tarakieffer** [comment]
Not sure if this is the only issue, but this is the one I am seeing with the data I have.  The count is not including both the tags and the entities.
 
In this example, I expect 'author' to have a count of six because of 2 items tagged with 'author' and 4 items with entity of 'author'

![screen shot 2015-01-12 at 1 15 01 pm](https://cloud.githubusercontent.com/assets/9256525/5709346/ae169d1e-9a5e-11e4-9b9c-2ac48e324a8e.png)

![screen shot 2015-01-12 at 1 15 21 pm](https://cloud.githubusercontent.com/assets/9256525/5709382/f852b61a-9a5e-11e4-8d2a-3f408cc5b524.png)
