### ISSUE TITLE
Users can surpass plan limits when uploading for first time

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#911]
Users on Pro plan able to upload more than one hour when uploading for first time (we don't calculate duration until after transcribe task runs).

**Comment by pkarman** [comment]
Do you have some specific examples?

**Comment by Saltzshaker** [comment]
Yep, I just noticed it with this user: https://www.popuparchive.com/superadmin/users/1615
She's trialing on the new plan for free as an AIR member.

**Comment by pkarman** [comment]
This was an edge case falling squarely in the Known Issue category of how our limits are currently enforced.

The first item she uploaded was fully transcribed at 2015-01-06 22:10:24 UTC
https://www.popuparchive.com/superadmin/tasks/312485

At that point the hourly cron job would have calculated her monthly usage and she would have been prevented from uploading anything else this month.

However, before the first transcription finished she uploaded another item at 2015-01-06 21:02:55 UTC
https://www.popuparchive.com/superadmin/tasks/312504
and it did not finish transcribing until 2015-01-06 22:18:29 UTC

So here was the order of events:

* 1st upload: 2015-01-06 18:02:07 UTC
* 2nd upload: 2015-01-06 21:02:55 UTC
* 1st transcript: 2015-01-06 22:10:24 UTC
* 2nd transcript: 2015-01-06 22:18:29 UTC

So the race condition is: usage is not calculated until the hourly job after the transcript finishes, so any uploads that happen before that time are not prevented.

We could switch our is_over_monthly_limit calculation to look at the total duration of all uploaded items, which would be better but not perfect, since duration is calculated asynchronously, after the upload is completed. Which means that if your first upload was all-by-itself greater than your monthly limit, we could not prevent it.

**Comment by pkarman** [comment]
I should also add: if we calculate monthly limits according to the audio duration, rather than the actual transcripts, we are then treating all audio as billable. So the transcript.is_billable? flag would be effectively ignored.

**Comment by pkarman** [comment]
I retract that last comment. The is_billable flag affects cost not time.
