### ISSUE TITLE
When user is added to org, org should receive collection grant to all collections with items

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#951]
When user joins an org, for each collection where items are >= 1
-Create a grant for org 
-Create owner role for org

**Comment by pkarman** [comment]
ready for testing in #958

**Comment by tarakieffer** [comment]
Tested by having francine added to Tara Test Org

superadmin view for francine before
![screen shot 2015-02-04 at 6 02 25 am](https://cloud.githubusercontent.com/assets/9256525/6040395/f06a1e2c-ac36-11e4-9529-57e395e6c3d6.png)

superadmin view for francine after
-My Uploads with 0 items is no longer authorized or billiable
-Fruit Salad with 0 items is no longer authorized, but still billable for francine- @pkarman/ @baileyspace  is this expected?
-Other collections that had more than one item are authorized for francine and billable under Tara Test Org
![screen shot 2015-02-04 at 6 28 21 am](https://cloud.githubusercontent.com/assets/9256525/6040404/1561ed36-ac37-11e4-919b-543965b27b4c.png)

**Comment by pkarman** [comment]
"Fruit Salad with 0 items is no longer authorized, but still billable for francine- @pkarman/ @baileyspace is this expected?"

Yes. That collection shows up as billable because it exists in the db, but not under authorized because it has been soft-deleted. Even though it has zero items, it is not hard-deleted. We could do that; I was erring on the side of keeping things.

**Comment by tarakieffer** [comment]
Since this is working as expected, I have marked this ready-to-deploy.
