### ISSUE TITLE
Transcribe tasks failing/canceled

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#953]
One more file for Bailey to bug archive.org about...

See https://www.popuparchive.com/api/collections/938/items/12468:
```{"id":17049,"filename":"1851451-3-1.wav","transcoded_at":"2014-06-13T22:13:52Z","duration":3224,"current_status":"Transcribing","url":["https://www.popuparchive.com/media/6f5d2bd0c17831abce634c19982ccdd2/0/public/audio_file/17049/1851451-3-1.mp3","https://www.popuparchive.com/media/f2ddf478a13b4cd5f1ef3e3fe5fa7e27/0/public/audio_file/17049/1851451-3-1.ogg"],"transcript_type":"Basic","premium_in_progress":false,"premium_retail_cost":"$19.72","transcript":null,"tasks":[{"id":319132,"status":"failed","name":null,"identifier":"ts_all","type":"transcribe"},{"id":319131,"status":"created","name":null,"identifier":"ts_start","type":"transcribe"},{"id":184140,"status":"cancelled","name":null,"identifier":"detect_derivatives","type":"detect_derivatives"},{"id":183422,"status":"cancelled","name":null,"identifier":"ts_all","type":"transcribe"},{"id":183421,"status":"cancelled","name":null,"identifier":"ts_start","type":"transcribe"},{"id":183419,"status":"complete","name":null,"identifier":null,"type":"analyze_audio"},{"id":183420,"status":"complete","name":null,"identifier":"ia://1eEvNVzFdccPIK6Y:1cURmhv6IFXAsPEl@studs-terkel-comments-and-presents-fiesta-a-chica.ClhL4c.popuparchive.org/1851451-3-1.wav?x-fixer-collections%5B%5D=popuparchive&x-fixer-metadata%5Bx-archive-meta-mediatype%5D=audio&x-fixer-metadata%5Bx-archive-meta-title%5D=Studs+Terkel+comments+and+presents+Fiesta%3A+a+Chicago+Happening+%3B+1969%2F03%2F12&x-fixer-subjects%5B%5D=Studs+Terkel","type":"copy"}]}```

As well as https://www.popuparchive.com/api/collections/938/items/12502, which she already emailed them about:
```{"id":35583,"filename":"1854440_3_2.wav","transcoded_at":"2014-12-28T00:11:10Z","duration":null,"current_status":"Processing","url":["https://www.popuparchive.com/media/b0e163428a3f4d719245f04084a3ddb8/0/public/audio_file/35583/1854440_3_2.mp3","https://www.popuparchive.com/media/6d8f3da05b7fce0c7836ec7e59c35e8a/0/public/audio_file/35583/1854440_3_2.ogg"],"transcript_type":"Basic","premium_in_progress":false,"premium_retail_cost":"$0.00","transcript":null,"tasks":[{"id":316171,"status":"cancelled","name":null,"identifier":"ts_all","type":"transcribe"},{"id":316170,"status":"cancelled","name":null,"identifier":"ts_start","type":"transcribe"},{"id":316105,"status":"cancelled","name":null,"identifier":null,"type":"analyze_audio"},{"id":314654,"status":"cancelled","name":null,"identifier":null,"type":"analyze_audio"},{"id":307913,"status":"cancelled","name":null,"identifier":null,"type":"analyze_audio"},{"id":307915,"status":"complete","name":null,"identifier":"detect_derivatives","type":"detect_derivatives"},{"id":307911,"status":"complete","name":null,"identifier":"ia://1eEvNVzFdccPIK6Y:1cURmhv6IFXAsPEl@alexander-tcherepnin-talks-with-studs-terkel-196.aEElLV.popuparchive.org/1854440_3_2.wav?x-fixer-collections%5B%5D=popuparchive&x-fixer-metadata%5Bx-archive-meta-mediatype%5D=audio&x-fixer-metadata%5Bx-archive-meta-title%5D=Jack+Conroy+talks+with+Studs+Terkel+on+WFMT+%3B+1962%2F03%2F28&x-fixer-subjects%5B%5D=Studs+Terkel","type":"copy"},{"id":307910,"status":"complete","name":null,"identifier":"cc5b45c6cd7fc46901074d803fed3afa53122641","type":"upload"}]}```

**Comment by baileyspace** [comment]
I've fixed these two, but going forward I think we can prevent this by
making sure that IA gets derivatives instead of the original_file_url.

This is where the url to use for processing is defined.

 def process_file_url
    return original_file_url if use_original_file_url? && original_file_url
    return file.url          if storage.is_public? && file.url
    destination
  end

And:

def url(*args)
    if has_file? and !file.nil?
      file.try(:url, *args)
    else
      original_file_url
    end
  end

Two things.

1) For IA items from Studs,  copy_media is set to false, so
use_original_file_url is true. And for these items, file.url ==
original_file_url. I think we could rewrite this line so that it tries to
get the mp3 `file.url('mp3')`, and move it before `return
original_file_url`, so that the preferred process_file_url is the mp3 for
all items.

But:
2) We're trying to transcribe these items before their derivatives are
detected. So for IA items we can choose to wait to start transcribing until
after the detect_derivatives task is complete.


---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-01-26 18:13 GMT-08:00 annewootton <notifications@github.com>:

**Comment by pkarman** [comment]
waiting to transcribe until detect_derivatives has finished makes sense to me in all cases. We must have a .mp3 to send to SM anyway.

**Comment by pkarman** [comment]
and there's no point in transcribing a .wav file; the .mp3 quality is just as good ime.
