### ISSUE TITLE
Should this Upload task have a status of 'Stuck'?

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#963]
https://stage.popuparchive.com/superadmin/items/24404
https://stage.popuparchive.com/superadmin/items/24403

This item has a status of "Processing," but the messaging indicates something went wrong.  

![screen shot 2015-01-28 at 9 52 25 pm](https://cloud.githubusercontent.com/assets/9256525/5952211/fc0e3ac8-a737-11e4-8a82-3e67a9448d7b.png)

**Comment by baileyspace** [comment]
Thar might have been because I was testing another branch. I redployed the
recover-button branch around same time, so let me know if you're still
having problems.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-01-28 19:57 GMT-08:00 Tara Kieffer <notifications@github.com>:

**Comment by tarakieffer** [comment]
Ah, thanks @baileyspace  - If I had been paying closer attention to my email, I would have seen it thanks to the deploy email.

I have other files upload just fine.  I was sort of hoping that I would get a stuck task for testing the recover button which probably skewed my perspective.

Is this scenario a legit situation to be considered - an item with just an Upload task still working?  Is there some point when it can be just assumed it failed?

**Comment by pkarman** [comment]
the Recover button should address stuck uploads as well. Have you tried clicking?

**Comment by tarakieffer** [comment]
Recover worked for these items.
