### ISSUE TITLE
premium plans should be able to reorder premium transcripts for older basic audio

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#964]
if a customer upgrades plans from basic to premium, they should be able to reorder premium transcripts for their older audio by clicking the same button as basic customers and have it count against their monthly usage w/o an overage or ondemand charge. 

This might already be true but opening this ticket to make sure we document the use case and result of testing.

**Comment by tarakieffer** [comment]
Testing shows these are getting a retail charge instead of counting towards the monthly limit.

**Comment by annewootton** [comment]
More recent testing shows that basic audio reprocessed from a paid plan is getting a retail charge AND counting toward monthly limit. This is increasingly an edge case since the community plan is changing to only provide premium transcripts, but we're leaving this ticket open to document the edge case.
