### ISSUE TITLE
Check that *valid* credit card is on file before reprocessing as premium

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#970]
Paul from WHS ordered premium transcripts and entered a credit card which was declined, but reprocessing still went through.

Find a way to check if card is valid before reprocessing as premium. (Or for that matter, while signing up or before upgrading plans, if we're not doing this already)

**Comment by pkarman** [comment]
for reference: https://support.stripe.com/questions/can-i-check-whether-a-card-is-valid-without-charging-it-at-the-same-time

**Comment by annewootton** [comment]
Hmm, I can't tell. Paul (cus_473bBYmySrqZEZ) entered the CC info last week
and it seemed to be successful, but his charge was declined immediately and
on every subsequent attempt I made (even when I added a name to the CC
details, since the card is not in Paul's name and he wondered if that was
the problem, though it can't possibly be, since we don't require anyone to
provide a billing name). Phew!

ᐧ

**Comment by annewootton** [comment]
Won't fix... seems like a fringe case that customers are even able to add credit cards that are subsequently declined (usually at moment of adding CC we're charging them, either for a plan or for pay-as-you-go)... so this *should* only affect apparently wacky fringe cases like Paul's OR when someone's CC has lapsed and then they order pay-as-you-go.
