### ISSUE TITLE
Check for files missing transcripts from before Bailey's Speechmatics speaker id fix

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#987]
After CUNY had issues on 2/4, Bailey put in a fix to catch when Speechmatics doesn't assign a final speaker ID. We haven't checked to see if any other files were affected by this in the past.

**Comment by pkarman** [comment]
we have a rake task that checks for missing transcripts but we have not run it in some time because many of the problems are due to bad or missing audio. Either failed uploads, or non-audio files uploaded, etc.

@annewootton : I'm not exactly sure what to test for here: audio that should have a premium transcript, but doesn't?

**Comment by annewootton** [comment]
Decided during standup that Peter will run a check on all Speechmatics jobs to make sure we've received proper callback.

**Comment by pkarman** [comment]
these audio_files created since 2015-01-01 are missing transcripts:
```
37333
39938
40135
40136
40137
40138
40139
40140
40141
40142
40453
40470
40472
40474
40475
40594
41099
41100
41110
41111
```

I checked them all, and with the exception of a couple, they are all legitimately missing: bad format, zero length or 404 not found. The couple that could be recovered, I recovered.
