### ISSUE TITLE
More graceful error handling

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#990]
Change when and how error messages show. Right now they're showing up all over the place during behavior like routine search queries.

**Comment by pkarman** [comment]
to be more explicit: there are API non-2xx responses during routine search queries that confuse users because they trigger error messages for the entire page.

(a) we should log these errors so that we can fix the actual problem
(b) we should be more graceful in what triggers an internal /error redirect and message

**Comment by pkarman** [comment]
this is in master.
